#!/usr/bin/env bash
#
# Builds the Rust core for the phone and regenerates the Kotlin bindings.
#
# Run this after any change to rust-core/src. The Kotlin side is generated
# from the compiled .so, not from the source, so skipping the regenerate step
# leaves the app calling an API the library no longer has - which shows up as
# a crash at the first call, not a compile error.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"
NDK="${ANDROID_NDK_HOME:-$HOME/dev/android-sdk/ndk/27.2.12479018}"
TARGET=aarch64-linux-android
# Matches the app's minSdk. The NDK ships one clang wrapper per API level, and
# the wrapper is what supplies the sysroot - bare clang will not work.
API=26

if [ ! -d "$NDK" ]; then
    echo "No NDK at $NDK. Set ANDROID_NDK_HOME." >&2
    exit 1
fi

# cloudkit-proto's build script shells out to protoc directly; without it the
# failure surfaces as an opaque build-script exit rather than a missing-tool
# message pointing at what to install.
if ! command -v protoc >/dev/null; then
    echo "No protoc on PATH. Install protobuf-compiler (apt: protobuf-compiler)." >&2
    exit 1
fi

BIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"

mkdir -p "$HERE/.cargo"
cat > "$HERE/.cargo/config.toml" << EOF
# Generated by build.sh - edit that instead.
[target.$TARGET]
linker = "$BIN/$TARGET$API-clang"
ar = "$BIN/llvm-ar"

[env]
CC_$TARGET = "$BIN/$TARGET$API-clang"
CXX_$TARGET = "$BIN/$TARGET$API-clang++"
AR_$TARGET = "$BIN/llvm-ar"
RANLIB_$TARGET = "$BIN/llvm-ranlib"
EOF

# rustpush uses the unstable `atomic_try_update` feature in auth.rs and lib.rs,
# so it cannot be built on stable. This is a property of the dependency, not a
# choice - stable fails with E0658 before it compiles a single line of ours.
echo "==> building $TARGET (release)"
cd "$HERE"
cargo +nightly build --release --target "$TARGET"

SO="$HERE/target/$TARGET/release/libimessage_core.so"

echo "==> generating Kotlin bindings"
# Library mode reads UniFFI metadata out of the compiled .so, which is why the
# generator is a separate crate that knows nothing about rustpush - building a
# host copy of the whole dependency tree just to emit Kotlin would cost more
# than the rest of this script combined.
if [ ! -x "$ROOT/bindgen/target/release/uniffi-bindgen" ]; then
    (cd "$ROOT/bindgen" && cargo build --release)
fi
"$ROOT/bindgen/target/release/uniffi-bindgen" generate \
    --library "$SO" \
    --language kotlin \
    --out-dir "$ROOT/app/src/main/java" \
    --no-format

echo "==> installing into jniLibs"
mkdir -p "$ROOT/app/src/main/jniLibs/arm64-v8a"
# Stripping takes the library from ~29MB to a few, which is most of the APK.
# The debug symbols are only useful with a native debugger attached, and the
# Rust side logs its own failures through android_logger anyway.
"$BIN/llvm-strip" --strip-all -o \
    "$ROOT/app/src/main/jniLibs/arm64-v8a/libimessage_core.so" "$SO"

ls -lh "$ROOT/app/src/main/jniLibs/arm64-v8a/libimessage_core.so"
echo "==> done"
