package com.leo.imessage.data

import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File

/**
 * The import, against a real file in the real format.
 *
 * This is the one path into the app that takes something it did not write
 * itself, which makes it the one place a silent misreading costs a
 * conversation rather than a frame. The fixture is generated by
 * `tools/make_test_export.py` - the same script that produces the large test
 * exports - so a change to either has to keep the other working.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class OpenBubblesImportTest {

    private lateinit var context: android.content.Context
    private lateinit var store: MessageStore
    private lateinit var attachmentDir: File

    @Before
    fun setUp() {
        context = ApplicationProvider.getApplicationContext()
        context.deleteDatabase("relay.db")
        store = MessageStore(context, File(context.filesDir, "history.json"))
        attachmentDir = File(context.cacheDir, "imported-test").apply { mkdirs() }
    }

    @After
    fun tearDown() {
        context.deleteDatabase("relay.db")
        attachmentDir.deleteRecursively()
    }

    private fun fixture() = checkNotNull(
        javaClass.classLoader?.getResourceAsStream("sample-export.obbackup")
    ) { "sample-export.obbackup is missing from test resources" }

    private suspend fun importFixture() = OpenBubblesImport.importStream(
        source = fixture(),
        attachmentDir = attachmentDir,
        store = store,
        contacts = null,
        myHandles = emptyList(),
    )

    @Test
    fun `an export becomes conversations`() = runTest {
        val result = importFixture()

        assertTrue("nothing was imported", result.chats > 0)
        assertTrue("no messages were imported", result.messages > 0)
        assertEquals(result.chats, store.chatsNow().size)
    }

    @Test
    fun `every imported message lands in a conversation that exists`() = runTest {
        importFixture()

        val known = store.chatsNow().map { it.id }.toSet()
        var seen = 0
        known.forEach { id ->
            store.messages(id).forEach {
                seen++
                assertEquals(id, it.chatId)
            }
        }
        assertTrue("the conversations came back empty", seen > 0)
    }

    @Test
    fun `each conversation shows its newest message`() = runTest {
        importFixture()

        store.chatsNow().forEach { chat ->
            val newest = store.messages(chat.id).maxByOrNull { it.timestamp }
            assertEquals(
                "${chat.id} is showing the wrong message",
                newest?.id,
                chat.lastMessage?.id,
            )
        }
    }

    @Test
    fun `reactions fold onto messages rather than becoming their own`() = runTest {
        importFixture()

        val all = store.chatsNow().flatMap { store.messages(it.id) }
        // A reaction is a row in the file. If it were imported as a message
        // the transcript would show a stream of blank bubbles.
        assertTrue("reaction rows leaked in", all.none { it.id.startsWith("tb-") })
        assertTrue("no reaction survived the import", all.any { it.tapbacks.isNotEmpty() })
    }

    @Test
    fun `importing the same file twice changes nothing`() = runTest {
        val first = importFixture()
        val before = store.chatsNow().size

        val second = importFixture()

        assertEquals(0, second.messages)
        assertEquals(0, second.chats)
        assertEquals(first.messages, second.duplicates)
        assertEquals(before, store.chatsNow().size)
    }

    @Test
    fun `attachments with no bytes import as references`() = runTest {
        importFixture()

        val attachments = store.chatsNow()
            .flatMap { store.messages(it.id) }
            .flatMap { it.attachments }
        assertTrue("the fixture has no attachments in it", attachments.isNotEmpty())
        // Nothing in the file claimed a bytes_id, so there is no local copy -
        // which is exactly the state a received attachment is in before it
        // has been downloaded.
        assertTrue("an attachment invented a file", attachments.all { it.uri == null })
        assertTrue(attachments.all { it.fileName.isNotBlank() })
    }

    @Test
    fun `it survives being handed something that is not an export`() = runTest {
        val rubbish = "this is not an export, it is a sentence".toByteArray()
        runCatching {
            OpenBubblesImport.importStream(
                source = rubbish.inputStream(),
                attachmentDir = attachmentDir,
                store = store,
                contacts = null,
                myHandles = emptyList(),
            )
        }.onSuccess { error("garbage was accepted as an export") }
            .onFailure {
                assertTrue(
                    "the failure does not say anything useful: ${it.message}",
                    it is IllegalArgumentException,
                )
            }
        // And the history it refused is still empty rather than half-written.
        assertEquals(0, store.chatsNow().size)
    }
}
